// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API_DOT_NET.Data;

#nullable disable

namespace WEB_API_DOT_NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918073453_villanumbers")]
    partial class villanumbers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API_DOT_NET.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Private Pool, Beach Access, Outdoor Dining",
                            CreatedDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxury beachfront villa with private pool and panoramic ocean views.",
                            ImageUrl = "https://images.unsplash.com/photo-1505691723518-36a5ac3b2a5d",
                            Name = "Sunset Paradise Villa",
                            Occupancy = 8,
                            Rate = 350.0,
                            Sqft = 2500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Fireplace, Hiking Trails, Hot Tub",
                            CreatedDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Secluded mountain retreat with fireplace, hiking trails, and scenic decks.",
                            ImageUrl = "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
                            Name = "Mountain Serenity Lodge",
                            Occupancy = 6,
                            Rate = 275.0,
                            Sqft = 1800,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Garden, BBQ Area, Outdoor Pool",
                            CreatedDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Tropical garden villa surrounded by palm trees, perfect for relaxation.",
                            ImageUrl = "https://images.unsplash.com/photo-1570129477492-45c003edd2be",
                            Name = "Palm Breeze Estate",
                            Occupancy = 10,
                            Rate = 400.0,
                            Sqft = 3200,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Private Dock, Canoe, Fireplace",
                            CreatedDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Charming lakeside villa with private dock and fishing access.",
                            ImageUrl = "https://images.unsplash.com/photo-1599423300746-b62533397364",
                            Name = "Lakeside Haven",
                            Occupancy = 5,
                            Rate = 220.0,
                            Sqft = 1500,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Rooftop Pool, City View, Concierge",
                            CreatedDate = new DateTime(2025, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Modern penthouse with skyline views, rooftop pool, and luxury interiors.",
                            ImageUrl = "https://images.unsplash.com/photo-1598928506310-4a03a2f9f2ed",
                            Name = "Urban Sky Penthouse",
                            Occupancy = 4,
                            Rate = 500.0,
                            Sqft = 1400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WEB_API_DOT_NET.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaNo");

                    b.ToTable("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
